
Teaching exercises week 1, algorithms in bioingotmatics

Exercise 1.1
Look at the exercise/example on slide 55 and forward in the slides from the lecture. Be sure that you understand how the dynamic programming table is filled according to the recursion, and how backtracking works.


In [ ]:

import numpy as np

cost_matrix = {'A': {'A': 0, 'T': 1, 'G': 1, 'C': 1},
                'T': {'A': 1, 'T': 0, 'G': 1, 'C': 1},
                'G': {'A': 1, 'T': 1, 'G': 0, 'C': 1},
                'C': {'A': 1, 'T': 1, 'G': 1, 'C': 0}}

def construct_matrix(i,j):
    return np.zeros((len(i)+1,len(j)+1))

def fill_out_matrix(seq1,seq2,cost_matrix):
    matrix = construct_matrix(seq1,seq2)
    for i in range(len(seq1)+1):
        for j in range(len(seq2)+1):
            if i==0 and j==0:
                matrix[i,j]=0
            elif i==0:
                matrix[i][j]=matrix[i][j-1]+1
            elif j==0:
                matrix[i][j]=matrix[i-1][j]+1
            else:
                left = matrix[i][j-1]+1
                above=matrix[i-1][j]+1
                diagonal=matrix[i-1][j-1]+cost_matrix[seq1[i-1]][seq2[j-1]]
                score=min(left,above,diagonal)
                matrix[i][j]=score
    return matrix

print(fill_out_matrix('AGGT','ACTA',cost_matrix))

Let A[i] be the i'th symbol in A[1..n], and let B[j] be the j'th symbol in B[1..m]. Let cost(A[i],B[j]) be the cost of aligning symbol A[i] against symbol B[j] in a substitution column. Let gapcost be the cost of a gap column. Using this notation, we can generalize the recursion on slide 62 as:
C(0,0) = 0
C(i,j) = min {C(i-1,j-1)+cost(A[i],B[j] if i>0 and j>0,
              C(i-1,j) + gapcost if i>0 and j>=0,
              C(i,j-1) + gapcost if i >=0 and j>0}



Exercise 1.2
Gap cost and score matrix: Given two strings A[1..n] and B[1..m], we know how to compute the optimal (minimum) cost of an alignment of these strings when a gap-column costs 1, and a substitution-column costs 0 if it aligns two identical symbols, and 1 otherwise. Using the scoring system, we say that the gapcost is 1, and that the score matrix is

  A C G T
A 0 1 1 1
C 1 0 1 1
G 1 1 0 1
T 1 1 1 0

if the two strings represent DNA sequences over the alphabet {A,C,G,T}.

How should we change the recursion/algorithm presented in the lecture if we want to compute the optimal cost of an alignment using a different gapcost and/or score matrix?

Answer: Just change the scores in the score_matrix and the gap_cost 


In the lecture, we defined the optimal cost of an alignment as the minimum cost. Sometimes it makes more sense to define the optimal score cost of an alignment as the maximum cost.

How should we change the recursion/algorithm presented in the lecture if we want to compute an alignment of maximum cost?

Change how we fill it out always choosing the max instead of the min. and when we traceback we should take it into account aswell.



In [ ]:
import numpy as np

cost_matrix = {'A': {'A': 1, 'T': 0, 'G': 0, 'C': 0},
                'T': {'A': 0, 'T': 1, 'G': 0, 'C': 0},
                'G': {'A': 0, 'T': 0, 'G': 1, 'C': 0},
                'C': {'A': 0, 'T': 0, 'G': 0, 'C': 1}}

def construct_matrix(i,j):
    return np.zeros((len(i)+1,len(j)+1))

def fill_out_matrix(seq1,seq2,cost_matrix):
    matrix = construct_matrix(seq1,seq2)
    for i in range(len(seq1)+1):
        for j in range(len(seq2)+1):
            if i==0 and j==0:
                matrix[i,j]=0
            elif i==0:
                matrix[i][j]=matrix[i][j-1]
            elif j==0:
                matrix[i][j]=matrix[i-1][j]
            else:
                left = matrix[i][j-1]+0
                above=matrix[i-1][j]+0
                diagonal=matrix[i-1][j-1]+cost_matrix[seq1[i-1]][seq2[j-1]]
                score=max(left,above,diagonal)
                matrix[i][j]=score
    return matrix

print(fill_out_matrix('AGGT','ACTA',cost_matrix))

which says that an optimal alignment is an alignment with minimum score. If we want that the an optimal alignment is an alignment with maximum score, then the above recursion should be:

C(0,0) = 0
C(i,j) = max {C(i-1,j-1)+cost(A[i],B[j] if i>0 and j>0,
              C(i-1,j) + gapcost if i>0 and j>=0,
              C(i,j-1) + gapcost if i>=0 and j>0}


Exercise 1.3
Unit cost edit distance: Given two strings A[1..n] and B[1..m], the unit cost edit distance is the minimum number of insertions, deletions, and substitutions of single symbols which can transform A into B. This number can be computed using the global alignment recursion (based on minimization) and a particular choice of score matrix and gap cost. Which score matrix and gap cost?




ANSWER: 
The same as above, but with a different cost matrix. 
If we want the score of an optimal alignment of A[1..n] and B[1..m] to be the edit distance between A and B, then we can use the score system from the lecture, i.e. where the score matrix is

  A C G T
A 0 1 1 1
C 1 0 1 1
G 1 1 0 1
T 1 1 1 0
and gapcost = 1 and the objective is to minimize the score. Here score of an alignment is the number of substitutions, insertions and deletions described by the alignment, i.e. the score of a minimum scoring alignment (an optimal alignment) is the edit distance.



Exercise 1.4
Longest common subsequence: Given two strings A[1..n] and B[1..m], the longest common subsequence (LCS) is the longest sequence of symbols which are subsequences of the two strings. E.g. an LCS of acgt and atgc is ag. This number can be computed using the global alignment recursion (based on maximization) and a particular choice of score matrix and gap cost. Which score matrix and gap cost?

If we want the score of an optimal alignment of A[1..n] and B[1..m] to be the legth of the longest common subsequence of A and B, then we can use a score system where the score matrix is

  A C G T
A 1 0 0 0
C 0 1 0 0
G 0 0 1 0
T 0 0 0 1

and gapcost = 0, and the objective is to maximize the score. Here the score of an alignment is the number of match column (i.e. substitutions of identical symbols), i.e. the score of a maximum scoring alignment (an optimal alignment) is the length of the longest common subsequence of A and B.


In [2]:
import numpy as np

cost_matrix = {'A': {'A': 1, 'T': 0, 'G': 0, 'C': 0},
                'T': {'A': 0, 'T': 1, 'G': 0, 'C': 0},
                'G': {'A': 0, 'T': 0, 'G': 1, 'C': 0},
                'C': {'A': 0, 'T': 0, 'G': 0, 'C': 1}}

def construct_matrix(i,j):
    return np.zeros((len(i)+1,len(j)+1))

def fill_out_matrix(seq1,seq2,cost_matrix):
    matrix = construct_matrix(seq1,seq2)
    for i in range(len(seq1)+1):
        for j in range(len(seq2)+1):
            if i==0 and j==0:
                matrix[i,j]=0
            elif i==0:
                matrix[i][j]=matrix[i][j-1]
            elif j==0:
                matrix[i][j]=matrix[i-1][j]
            else:
                left = matrix[i][j-1]+0
                above=matrix[i-1][j]+0
                diagonal=matrix[i-1][j-1]+cost_matrix[seq1[i-1]][seq2[j-1]]
                score=max(left,above,diagonal)
                matrix[i][j]=score
    return matrix

print(fill_out_matrix('AGGGG','AGGGGTC',cost_matrix))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2. 2. 2.]
 [0. 1. 2. 3. 3. 3. 3. 3.]
 [0. 1. 2. 3. 4. 4. 4. 4.]
 [0. 1. 2. 3. 4. 5. 5. 5.]]


Exercise 1.5
Number of possible alignments: Give a non-trivial lower- and upper-bound of the number of possible alignments of two strings of length n. Can you make a program that counts the exact number of possible alignments of two strings of lengths n and m?


In [28]:
def possible_alignments_rec(n,m):
    if n==0 or m==0:
        return 1
    else:
        return possible_alignments(n-1,m)+possible_alignments(n,m-1)

#non recursive
def factorial(x):
    if x==0:
        return 1
    else:
        return x*factorial(x-1)

def possible_alignments(n,m):
    return factorial(m+n)/(factorial(m)*factorial(n))



print(possible_alignments(2,2))

print(possible_alignments_rec(2,2))



6.0


An alignment of A[1..n] and B[1..m] has at most n+m columns. Since each of these columns can be chosen among at most three types of columns (substitution, insertion and deletion), theb there are atmost 

3^{n+m}

alignments of A and B. Since an alignment of A and B has at least min(n,m) columns that can be chosen among the three types of columns, then there is at least

3^min(n,m)

alignments of A and B.

Exercise 1.6
In the mandatory projects, you will be asked to implement various algorithm. This also includes reading data from files. In the first projects, this will be sequence data stored in FASTA-files. You can use any programming languages and libraries you want. If you use Python, then Biopython (in particular Bio.SeqIO is useful for handling data stores in FASTA files) or scikit-bio are useful libraries. The Biopython Tutorial and Cookbook contains good documents of how to use Biopython. Write a small program that can read in a sequence from a FASTA-files using a programming language of your choice, e.g. Python in combination of Biopython.  You can use the FASTA files referred to in project


In [29]:
from Bio import SeqIO

def fasta_parser(input_file,output_file):
    with open(input_file,'r') as f:
        for fasta in SeqIO.parse(f,'fasta'):
            name, sequence = fasta.id, fasta.seqpib
            with open(output_file,'w') as q:
                q.write('>')
                q.write(name)
                q.write('\n')
                print(str(sequence))
                q.write(str(sequence))
    return None

def fasta_seq(input_file):
    seqs = []
    with open(input_file,'r') as f:
        for fasta in SeqIO.parse(f,'fasta'):
            name, sequence = fasta.id, fasta.seq
            seqs.append(str(sequence))
    return seqs


a = 'seq1.fasta'
b = 'test.fasta'


class fasta:
    def __init__(self,fasta_file):
        self.fasta_file = fasta_file
        self.sequences = []
        self.names = []
        self.parse_fasta()
    def parse_fasta(self):
        with open(self.fasta_file,'r') as f:
            for fasta in SeqIO.parse(f,'fasta'):
                name, sequence = fasta.id, fasta.seq
                self.sequences.append(str(sequence))
                self.names.append(name)
    def get_sequences(self):
        return self.sequences
    def get_names(self): 
        return self.names

